project_id = "fwdptrrdhgkruvvctcns"

[functions.chat]
verify_jwt = false

[functions.sarvam-translate]
verify_jwt = false

[functions.sarvam-stt]
verify_jwt = false

[functions.sarvam-tts]
verify_jwt = false

[functions.describe-image]
verify_jwt = false

[functions.web-crawl]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.web-search]
verify_jwt = false
