import { useState, useRef } from "react";
import { FileDown, Loader2, Sparkles, RotateCcw } from "lucide-react";
import { cn } from "@/lib/utils";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";

const TEMPLATES = [
  { id: "study-plan", label: "📚 Study Plan", placeholder: "e.g. 30-day React mastery plan for intermediate developers" },
  { id: "report", label: "📊 Report", placeholder: "e.g. Market analysis report for AI SaaS startups in 2026" },
  { id: "checklist", label: "✅ Checklist", placeholder: "e.g. Production deployment checklist for Node.js apps" },
  { id: "guide", label: "📖 Guide", placeholder: "e.g. Complete guide to system design interviews" },
  { id: "resume", label: "📄 Resume Content", placeholder: "e.g. Senior frontend developer resume with 5 years React experience" },
  { id: "custom", label: "✨ Custom", placeholder: "Describe exactly what document you need..." },
];

function markdownToHtml(md: string): string {
  return md
    .replace(/^### (.+)$/gm, '<h3 style="font-size:14px;font-weight:700;margin:18px 0 8px;color:#1a1a2e;">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 style="font-size:17px;font-weight:700;margin:24px 0 10px;color:#0f0f23;border-bottom:1px solid #e5e7eb;padding-bottom:6px;">$1</h2>')
    .replace(/^# (.+)$/gm, '<h1 style="font-size:22px;font-weight:800;margin:0 0 16px;color:#0f0f23;">$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/^- (.+)$/gm, '<li style="margin:3px 0;margin-left:20px;list-style:disc;">$1</li>')
    .replace(/^(\d+)\. (.+)$/gm, '<li style="margin:3px 0;margin-left:20px;list-style:decimal;">$2</li>')
    .replace(/\n{2,}/g, '<br/><br/>')
    .replace(/\n/g, '<br/>');
}

function generatePdfBlob(content: string, title: string): Blob {
  const html = markdownToHtml(content);
  const fullHtml = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${title}</title>
<style>
  @page { margin: 40px 50px; }
  body { font-family: 'Segoe UI', system-ui, sans-serif; font-size: 13px; line-height: 1.7; color: #1a1a2e; max-width: 700px; margin: 0 auto; padding: 40px 50px; }
  h1 { border-bottom: 2px solid #6366f1; padding-bottom: 8px; }
  h2 { color: #4f46e5; }
  li { padding-left: 4px; }
  strong { color: #0f0f23; }
</style></head><body>${html}
<div style="margin-top:40px;padding-top:16px;border-top:1px solid #e5e7eb;font-size:10px;color:#9ca3af;text-align:center;">
Generated by Quanta AI · ${new Date().toLocaleDateString()}
</div></body></html>`;

  return new Blob([fullHtml], { type: "text/html" });
}

export default function TaskExecutorTool() {
  const { user } = useAuth();
  const [template, setTemplate] = useState("study-plan");
  const [task, setTask] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const currentTemplate = TEMPLATES.find(t => t.id === template)!;

  const execute = async () => {
    if (!task.trim()) return;
    setLoading(true);
    setResult(null);
    setError(null);

    try {
      const { data, error: fnError } = await supabase.functions.invoke("task-executor", {
        body: { task: task.trim(), format: template },
      });

      if (fnError) throw new Error(fnError.message);
      if (data?.error) throw new Error(data.error);
      if (!data?.content) throw new Error("No content generated");

      setResult(data.content);
    } catch (err: any) {
      setError(err.message || "Generation failed");
    } finally {
      setLoading(false);
    }
  };

  const downloadHtml = () => {
    if (!result) return;
    const blob = generatePdfBlob(result, task.slice(0, 50));
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${template}-${Date.now()}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const printAsPdf = () => {
    if (!result) return;
    const blob = generatePdfBlob(result, task.slice(0, 50));
    const url = URL.createObjectURL(blob);
    const win = window.open(url, "_blank");
    if (win) {
      win.onload = () => {
        setTimeout(() => { win.print(); }, 500);
      };
    }
    // cleanup after delay
    setTimeout(() => URL.revokeObjectURL(url), 10000);
  };

  const reset = () => {
    setResult(null);
    setError(null);
    setTask("");
    setTimeout(() => textareaRef.current?.focus(), 100);
  };

  // ── Result view ──
  if (result) {
    return (
      <div className="flex flex-col h-full max-w-2xl mx-auto animate-fade-in">
        <div className="shrink-0 flex items-center justify-between px-4 py-3 border-b border-border/40">
          <div className="flex items-center gap-2">
            <FileDown className="w-4 h-4 text-primary" />
            <span className="text-sm font-semibold text-foreground">Document Ready</span>
          </div>
          <button onClick={reset} className="p-1.5 rounded-md text-muted-foreground hover:text-foreground hover:bg-muted transition-colors">
            <RotateCcw className="w-3.5 h-3.5" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto px-4 py-4">
          <div className="prose prose-sm max-w-none text-foreground/80 whitespace-pre-wrap text-sm leading-relaxed border border-border/30 rounded-xl p-4 bg-card">
            {result}
          </div>
        </div>

        <div className="shrink-0 px-4 py-3 border-t border-border/40 flex gap-2">
          <button
            onClick={printAsPdf}
            className="flex-1 px-4 py-2.5 rounded-xl bg-primary text-primary-foreground text-sm font-medium hover:opacity-90 transition-opacity flex items-center justify-center gap-2"
          >
            <FileDown className="w-4 h-4" />
            Save as PDF
          </button>
          <button
            onClick={downloadHtml}
            className="px-4 py-2.5 rounded-xl border border-border text-sm text-foreground hover:bg-muted transition-colors"
          >
            Download HTML
          </button>
        </div>
      </div>
    );
  }

  // ── Input view ──
  return (
    <div className="max-w-lg mx-auto p-4 space-y-6 animate-fade-in flex flex-col items-center justify-center h-full">
      <div className="text-center space-y-2">
        <div className="w-14 h-14 rounded-2xl bg-primary/10 flex items-center justify-center mx-auto mb-3">
          <Sparkles className="w-7 h-7 text-primary" />
        </div>
        <h2 className="text-xl font-bold text-foreground">Task Executor</h2>
        <p className="text-sm text-muted-foreground">Describe a task → get a downloadable document</p>
      </div>

      <div className="w-full max-w-sm space-y-4">
        {/* Template selector */}
        <div>
          <label className="text-xs font-medium text-muted-foreground mb-1.5 block">Document type</label>
          <div className="flex gap-1.5 flex-wrap">
            {TEMPLATES.map(t => (
              <button
                key={t.id}
                onClick={() => setTemplate(t.id)}
                className={cn(
                  "px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors",
                  template === t.id
                    ? "border-primary/30 bg-primary/10 text-primary"
                    : "border-border text-muted-foreground hover:bg-muted"
                )}
              >
                {t.label}
              </button>
            ))}
          </div>
        </div>

        {/* Task input */}
        <div>
          <label className="text-xs font-medium text-muted-foreground mb-1.5 block">What do you need?</label>
          <textarea
            ref={textareaRef}
            value={task}
            onChange={(e) => setTask(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && e.metaKey) {
                e.preventDefault();
                execute();
              }
            }}
            placeholder={currentTemplate.placeholder}
            className="w-full resize-none bg-muted/30 border border-border rounded-xl outline-none text-sm text-foreground p-3 min-h-[100px] max-h-[160px] focus:border-primary/30 transition-colors placeholder:text-muted-foreground/50"
          />
        </div>

        {error && (
          <p className="text-xs text-destructive bg-destructive/10 rounded-lg px-3 py-2">{error}</p>
        )}

        <button
          onClick={execute}
          disabled={!task.trim() || loading}
          className="w-full px-4 py-3 rounded-xl bg-primary text-primary-foreground font-medium text-sm hover:opacity-90 transition-opacity disabled:opacity-30 flex items-center justify-center gap-2"
        >
          {loading ? (
            <>
              <Loader2 className="w-4 h-4 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <Sparkles className="w-4 h-4" />
              Generate Document
            </>
          )}
        </button>

        <p className="text-[10px] text-muted-foreground/50 text-center">⌘+Enter to generate · Opens print dialog for PDF save</p>
      </div>
    </div>
  );
}
