import { useState } from "react";
import { Eye, Loader2, Download } from "lucide-react";

export default function VisionTool() {
  const [text, setText] = useState("");
  const [title, setTitle] = useState("Document");
  const [generating, setGenerating] = useState(false);

  const generatePDF = () => {
    if (!text.trim()) return;
    setGenerating(true);

    try {
      // Create a printable HTML document
      const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title}</title>
  <style>
    body { font-family: 'Georgia', serif; max-width: 700px; margin: 40px auto; padding: 20px; line-height: 1.8; color: #222; }
    h1 { font-size: 24px; border-bottom: 2px solid #333; padding-bottom: 8px; margin-bottom: 20px; }
    p { margin-bottom: 12px; text-align: justify; }
    .footer { margin-top: 40px; padding-top: 10px; border-top: 1px solid #ccc; font-size: 12px; color: #888; text-align: center; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  ${text.split("\n").filter(Boolean).map((p) => `<p>${p}</p>`).join("\n")}
  <div class="footer">Generated by Quanta Vision Tool</div>
</body>
</html>`;

      const blob = new Blob([htmlContent], { type: "text/html" });
      const url = URL.createObjectURL(blob);
      
      // Open in new window for printing as PDF
      const printWindow = window.open(url, "_blank");
      if (printWindow) {
        printWindow.onload = () => {
          printWindow.print();
        };
      }

      // Also offer direct HTML download
      const a = document.createElement("a");
      a.href = url;
      a.download = `${title.replace(/\s+/g, "_")}.html`;
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="max-w-2xl mx-auto p-4 space-y-4 animate-fade-in">
      <div className="flex items-center gap-2 mb-2">
        <Eye className="w-5 h-5 text-primary" />
        <h2 className="text-lg font-semibold text-foreground">Vision — Text to Document</h2>
      </div>

      <input
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        placeholder="Document title..."
        className="w-full bg-muted/50 border border-border rounded-xl px-3 py-2 text-sm text-foreground outline-none focus:border-primary/30"
      />

      <textarea
        value={text}
        onChange={(e) => setText(e.target.value)}
        placeholder="Enter or paste your text here. It will be converted into a printable document (PDF via browser print)..."
        className="w-full bg-muted/50 border border-border rounded-2xl outline-none text-sm text-foreground p-4 min-h-[200px] resize-none focus:border-primary/30 transition-colors"
      />

      <div className="flex items-center gap-3">
        <button onClick={generatePDF} disabled={!text.trim() || generating} className="flex items-center gap-2 px-6 py-2.5 rounded-xl bg-primary text-primary-foreground text-sm font-medium hover:opacity-90 disabled:opacity-30 transition-opacity">
          {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
          Generate Document
        </button>
        {text.length > 0 && <span className="text-xs text-muted-foreground">{text.length.toLocaleString()} chars</span>}
      </div>
    </div>
  );
}
